add Show Conan profile in ci.yml add Show toolchain versions in ci.yml move Check code style job to ci.yml delete check_code_style.yml add Setup ccache for speed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,13 +9,46 @@ permissions:
   contents: read
 
 concurrency:
-  group: ci-${{ github.ref }}
-  cancel-in-progress: true
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
 
 jobs:
-  build-and-test:
+  clang-format:
+    name: Check code style
     runs-on: ubuntu-latest
-    timeout-minutes: 30
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Verify .clang-format exists
+        run: test -f .clang-format || (echo "::error ::.clang-format not found" && exit 1)
+
+      - name: Install clang-format
+        run: python -m pip install clang-format==18.1.8
+
+      - name: Show clang-format version
+        run: clang-format --version
+
+      - name: Check formatting
+        run: |
+          find . \
+          -path './.git' -prune -o \
+          -path './build' -prune -o \
+          -path './cmake-build-*' -prune -o \
+          -type f \( \
+          -name '*.cpp' -o \
+          -name '*.hpp' -o \
+          -name '*.cc' -o \
+          -name '*.cxx' -o \
+          -name '*.h' -o \
+          -name '*.c' \
+          \) \
+          -exec clang-format --dry-run --Werror --style=file {} +
+
+  build-and-test:
+    name: Build and Test project
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
 
     steps:
       - uses: actions/checkout@v4
@@ -23,8 +56,10 @@ jobs:
       - name: Install Conan
         run: pipx install "conan>=2,<3"
 
-      - name: Detect Conan profile
-        run: conan profile detect --force
+      - name: Detect and Show Conan profile
+        run: |
+          conan profile detect --force
+          conan profile show
 
       - name: Cache Conan packages
         uses: actions/cache@v4
@@ -33,11 +68,26 @@ jobs:
           key: conan-${{ runner.os }}-${{ hashFiles('conanfile.py') }}
           restore-keys: conan-${{ runner.os }}-
 
+      - name: Setup ccache
+        uses: hendrikmuhs/ccache-action@v1.2
+        with:
+          key: ${{ github.job }}-${{ runner.os }}
+
       - name: Conan install
         run: conan install . -s build_type=Release -s compiler.cppstd=20 -b missing
 
+      - name: Show toolchain versions
+        run: |
+          cmake --version
+          gcc --version
+          g++ --version
+          conan --version
+
       - name: Configure
-        run: cmake --preset release-default
+        run: >
+          cmake --preset release-default
+          -DCMAKE_C_COMPILER_LAUNCHER=ccache
+          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
 
       - name: Build
         run: cmake --build --preset release-release
